### PR TITLE
Removes trailing slashes in the router

### PR DESCRIPTION
**Pull request by atellmer**
[Linked issue](https://github.com/atellmer/dark/issues/48)

### CODE REVIEW

**Comment by atellmer** [comment]
it needs some tests

**Comment by Coachonko** [comment]
I am looking at the changes.
I think `const { path } = useMatch()` should always return trailing slashes (consistency for developers)

- paths in route definitions should ignore trailing slashes
```js
  {
    path: '/contact/',
    component: lazy(() => import('../pages/Contact')),
  },
  // result is the same as 
    {
    path: '/contact',
    component: lazy(() => import('../pages/Contact')),
  },
  // either one of these match both base/contact and base/contact/
```
- I think the users should only get paths without trailing slashes (what ends up in browser url bar)

**Comment by atellmer** [comment]
I used `react-router-dom` before and, as far as I remember, the matched path was with a trailing slash.
But on the other hand, without the trailing slash, you can write links to nested routes like this:
const { url } = useMatch();

```tsx
<RouterLink to={`${url}/list`}>List</RouterLink>
```

instead of
```tsx
<RouterLink to={`${url}list`}>List</RouterLink>
```

Which option is better in your opinion?

**Comment by Coachonko** [comment]
Not adding a slash every time is more convenient and matches the behavior of bash utilities such as `pwd`. 
Would the root path be `/` or ` ` in this situation?
It makes more sense to me, but if the majority of users expect trailing slashes it should return trailing slashes.

I can't speak for the majority, but I do think a large amount of people use React.
For sure, whichever option is chosen I do think it should be consistent: either always with trailing slashes or always without

**Comment by atellmer** [comment]
With current changes in the branch I see this

```tsx
const routes: Routes = [
  {
    path: '/contacts',
    component: Contacts,
  },
  {
    path: '/about',
    component: About,
  },
  {
    path: '/',
    component: Home,
  },
  {
    path: '**',
    redirectTo: '/contacts',
  },
];
```

```tsx
{path: '/', url: '/'} // match for home
{path: '/contacts', url: '/contacts'}  // match for contacts
```

We can think about root path here as a **start slash**, but not **trailing slash**. From this point of view everything here is normal. Any toughts?

**Comment by Coachonko** [comment]
To me this seems good. Though I don't trust my opinion 😂
matchPath on wild then returns `{path: '/**'}`? Seems good to me

**Comment by atellmer** [comment]
For wildcard (**) it will be also `{path: 'contacts', url: '/contacts'}` because it's redirect.
If you define wildcard as component, it will be `{path: '**', url: '/**'}` but url /** is bug apparently.

**Comment by Coachonko** [comment]
> url /** is bug apparently. But I don't know maybe it's feature? =)

I don't really know, I never matched a url because they're different on browser and server

**Comment by atellmer** [comment]
So, it will be featrure 🫡

**Pull request merged**
